### PR TITLE
Add amsross/full-fmap

### PR DESCRIPTION
**Pull request by amsross**
https://github.com/amsross/pull-fmap

> fmap function for mapping over functors in a pull stream

### CODE REVIEW

**Comment by dominictarr** [comment]
what is a functor? is this for if you have a stream of functions?

**Comment by amsross** [comment]
A functor is a data type that implements a `map` function in such a way that is meets these expectations:
> 1. `u.map(a => a)` is equivalent to `u` (identity)
> 2. `u.map(x => f(g(x)))` is equivalent to `u.map(g).map(f)` (composition)
> 3. `f` must be a function
>   i. If `f` is not a function, the behaviour of `map` is unspecified.
>   ii. `f` can return any value.
>   iii. No parts of `f`'s return value should be checked.
> 4. `map` must return a value of the same Functor
>
>  per [`fantasyland/fantasy-land#functor`](https://github.com/fantasyland/fantasy-land#functor)

Some common examples of functors are [`Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) and [`fantasyland/fantasy-maybes`](https://github.com/fantasyland/fantasy-maybes).

You could use these like so:
```
pull(
  pull.values([ Just('Hello'), Just('World'), Nothing ])
  fmap(x => x.toUpperCase()),
  pull.log())
// Just(HELLO)
// Just(WORLD)
// Nothing
```
or
```
pull(
  pull.values([["hello", world"], ["i'm", "here"]]),
  fmap(x => x.toUpperCase()),
  pull.log())
// ["HELLO", "WORLD"]
// ["I'M", "HERE"]
```

Some references:
 * https://en.wikipedia.org/wiki/Functor
 * https://medium.com/@dtinth/what-is-a-functor-dcf510b098b6#.8ssdfkdsr and https://medium.com/@romaklimenko/this-is-not-a-precise-definition-687d19a88bb3#.5pya4rgl9
 * https://drboolean.gitbooks.io/mostly-adequate-guide/content/ch8.html#my-first-functor
 * https://egghead.io/lessons/javascript-you-ve-been-using-functors

**Comment by ahdinosaur** [comment]
@amsross sweet, thanks!

**Comment by dominictarr** [comment]
@amsross so a "functor" is just a thing that has `.map()` (or can be mapped?)
looked at your code and answered my own question. https://github.com/amsross/pull-fmap/blob/master/index.js#L8

They could have called it a "mappable" though. A big problem with functional programming is all the weird terms.

**Comment by amsross** [comment]
@dominictarr I'd refer you to the second and third references above. In the second, the author says that a functor is "a thing that can be mapped... A mappable." The third goes is a comment on that statement and how that statement, while technically true, is "not precise enough."

These terms come from mathematics where they represent very specific data and logic constructs.

**Pull request merged**
