### PR TITLE
Add dignifiedquire/pull-length-prefixed

### LINKED ISSUE #1: add to pull-stream.github.io modules?
hey @dignifiedquire, awesome module!

just wondering, would you like this added to <https://pull-stream.github.io>? the process to add a module is as easy as pull request-ing a change to [pull-stream-docs/modules.md](https://github.com/pull-stream/pull-stream-docs/blob/master/modules.md), keen to include any modules that want to be a part of the ecosystem.

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes https://github.com/dignifiedquire/pull-length-prefixed/issues/1

### CODE REVIEW

**Comment by ahdinosaur** [comment]
[merged](https://github.com/pull-stream/pull-stream-docs/commit/a46c66fc9232e0513d3e88950170adec234d90bb) and [deployed](https://pull-stream.github.io/#/pull-length-prefixed), thanks!

**Comment by dominictarr** [comment]
@dignifiedquire you might also like https://github.com/dominictarr/pull-varstruct

**Comment by dignifiedquire** [comment]
@dominictarr nice :) now I just need to write one that handles protobufs

**Comment by yoshuawuyts** [comment]
@dignifiedquire yes please! - protobuf pull streams would be amazing :sparkles:

**Pull request merged**
