### PR TITLE
Add jamen/pull-fs-meta

### PR DESCRIPTION
**Pull request by jamen**
Hello, back with another module, [`pull-fs-meta`](https://github.com/jamen/pull-fs-meta).  This one is experimental, but seems to be pretty cool so far.  It's my approach to an `fs` module on `pull-stream`.

It appears to operate much like `Vinyl`inside `gulp`, except it actually just streams the file contents, and manages the metadata behind the scenes.  That way you can have reusable `pull-*` modules that compile contents (like `pull-css`) operate like a build system with this, without need to create wrappers and whatnot:

``` js
var fs = require('pull-fs-meta')()
var css = require('pull-css')

pull(
  // Read file contents:
  fs.read('out/*.css'),
  // Parse contents as CSS:
  css(),
  // Then transform AST, like PostCSS
  // Stringify it after transformed:
  css.stringify(),
  // And write out
  fs.write('out')
)
```

### CODE REVIEW

**Comment by dominictarr** [comment]
curious: does this return a stream of streams, or does it concatenate all the streams?

**Comment by dominictarr** [comment]
it might be interesting to use with http://npm.im/tar-fs

**Comment by jamen** [comment]
> does this return a stream of streams, or does it concatenate all the streams?

I don't understand completely :sweat_smile:.  But I'm pretty sure it doesn't return streams of streams.  Maybe I can explain.

The functions are created in a factory:

``` js
var fs = require('pull-fs-meta')()
```

They share this private array called `meta` in that scope.  This avoid having to put it on/around the contents itself (like `Vinyl`).

`fs.read` resolves globs to paths then reads to contents, and pushes metadata on `meta` about the file is just read. (For now just `[path, base]`).  Each read correlates with an index on `meta`.

`fs.files` is a passthrough stream that is made for changing `meta`.  (For things like extension name, moving files, clearing the metadata, etc.)

`fs.write` keeps an index for each write call so it can pick the info from `meta` with the correlating `contents` it read.  (Because the 1:1 read/write ratio)

**Comment by jamen** [comment]
I'm going to redo the name and stuff.  I'll open up a new PR later.

**Pull request closed without merging**
