### PR TITLE
Add `pull-combine-latest`

### PR DESCRIPTION
**Pull request by nichoth**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
sweet module, thanks @nichoth!

**Comment by ahdinosaur** [comment]
deployed: https://pull-stream.github.io/#pull-combine-latest :tada: 

(side note: i think your face is missing from the page because [your commits are not recognized as your GitHub account](https://github.com/nichoth/pull-combine-latest/commits/master).)

**Comment by nichoth** [comment]
Thanks @ahdinosaur . I was wondering why my picture was anonymous, and I finally fixed it.

**Comment by ahdinosaur** [comment]
great, re-deployed and now you're there.

**Pull request merged**
